### PR TITLE
GuzzleHttp 5.2 library.

### LINKED ISSUE #13: Guzzle library deprecated.
The Guzzle library is deprecated, GuzzleHttp is now preferred.

### PR DESCRIPTION
**Pull request by bweston92**
fixes #13

### CODE REVIEW

**Comment by brunogaspar** [comment]
Thanks, i've fixed the Guzzle request, as it was still using the old way.

Will have it merged to 1.1 and 2.0 with the appropriate tags later.

**Comment by GrahamCampbell** [comment]
Any reason we need 5.2 as a minimum, and not 5.0?

**Comment by bweston92** [comment]
Not really just making sure people stay up to date.



—

**Comment by GrahamCampbell** [comment]
This could unltilately just lead to dependency conflicts meaning people actually end up out of date.

**Pull request merged**
