### PR TITLE
Fix array_get typos in ConverterServiceProvider

### PR DESCRIPTION
**Pull request by rawcreative**
Fix `array_gey()` typos in registerExchangers method.

### CODE REVIEW

**Comment by brunogaspar** [comment]
Nice catch, it's a funny typo haha

Thanks!

**Comment by rawcreative** [comment]
Yeah I must say I had a chuckle when I saw it.. :)

**Comment by brunogaspar** [comment]
Ya haha :)

Tagged 2.0.1, thanks again for the fix.

**Comment by drsii** [comment]
Awesome catch @rawcreative hehe.

**Pull request merged**
